import Head from "next/head";
import { Container, Main } from "../components/sharedstyles";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Chimera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/assets/logo.png" />
        <link
          href="https://fonts.cdnfonts.com/css/neue-haas-grotesk-display-pro"
          rel="stylesheet"
        />
      </Head>
      <Main></Main>
    </Container>
  );
}
